name: Deploy to EC2

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Optional: add GitHub's SSH host key to known_hosts to prevent host verification
        ssh-keyscan -H 3.95.19.248 >> ~/.ssh/known_hosts  # replace with your EC2 IP address

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@3.95.19.248 << 'EOF'
          # Add your deployment commands here, e.g.,
          cd /path/to/your/app
          git pull origin main
          # or other commands to deploy your app
          echo "Deployment finished"
        EOF
